### PR TITLE
V0.3.0 alpha.1

### PR DESCRIPTION
**Pull request by almindor**
Support for embedded-hal v1.0.0-alpha.8

### CODE REVIEW

**Comment by mixedCase** [comment]
Would be great to see this happen! esp-idf-hal is currently reliant on newer embedded-hal and I'm unable to get esp-idf-hal to play nice with mipidsi.

**Comment by almindor** [comment]
> Would be great to see this happen! esp-idf-hal is currently reliant on newer embedded-hal and I'm unable to get esp-idf-hal to play nice with mipidsi.

I'm really busy atm. trying to also finish a refactor. I will happily do an alpha pre-release if someone is willing to update this to latest on both ends. If not I might get to it in a month or so.

**Comment by mixedCase** [comment]
@almindor Opened #41. Very much a Rust newb, let me know if the error handling was way off.

**Comment by almindor** [comment]
Deprecated

**Pull request closed without merging**
