### PR TITLE
take init seq from st7789

### LINKED ISSUE #1: Colors seems to be inverted
Hi !

I tested this new implementation [here](https://github.com/pyaillet/ttgo-display-idf-rs/blob/8709f33701ef3283fa444455eba01dbd2d5f18e2/src/main.rs). I faced a strange bug, it seems colors are inverted (See picture below).

I will have a look a make a PR if I can identify the problem and a solution.

IMG_20220223_205821

### PR DESCRIPTION
**Pull request by pyaillet**
Fix #1 

So with the other changes I was able to test and validate this setup on both TTGO Display and TTGO TWatch-2020 v1.

Anyway I admit, I'm not sure to understand every commands of the init seq, so do not hesitate to correct me if something is odd.

### CODE REVIEW

**Comment by almindor** [comment]
I've almost finished my wiring setup to get the ST7789 wired to another MCU (I kinda lost the pinetime) so I should be able to test this in the coming days. Hope that's ok.

**Comment by almindor** [comment]
Having some issues with my old ST7789, currently trying to figure it out with a logic analyzer. I don't think this has anything to do with the code tho. If I can't get it working I'll probably just merge this as I don't have another display to test with, the pinetime watch got damaged ages ago.

**Comment by pyaillet** [comment]
No problem :)

Let me know if I can do anything to help.

**Comment by almindor** [comment]
> No problem :)
> 
> Let me know if I can do anything to help.

Do you have a logic analyzer? Could you send me a capture of the "shapes" example draw code in say 1Mhz speed?

**Comment by pyaillet** [comment]
No, I don't have one :\

**Comment by almindor** [comment]
No isses. I'll have to probably get a new display and possibly an MCU too to be sure. something's wrong with my hw here.

**Pull request merged**
